# Generated by Django 6.0.1 on 2026-02-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_receipt_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receiptitem',
            name='category_snapshot',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='receiptitem',
            index=models.Index(fields=['receipt'], name='store_recei_receipt_61a47d_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptitem',
            index=models.Index(fields=['product'], name='store_recei_product_113c34_idx'),
        ),
        migrations.AddIndex(
            model_name='receiptitem',
            index=models.Index(fields=['category_snapshot'], name='store_recei_categor_5f1fdf_idx'),
        ),
    ]
